#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.2
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  56
yabai -m config bottom_padding               16
yabai -m config left_padding                 16
yabai -m config right_padding                16
yabai -m config window_gap                   8

yabai -m config window_shadow                   float

yabai -m space 1 --label "Web"
yabai -m space 2 --label "Code"
yabai -m space 3 --label "Prod"
yabai -m space 4 --label "Misc"

yabai -m rule --add app="Google Chrome" space=1
yabai -m rule --add app="Firefox" space=1
yabai -m rule --add app="Visual Studio Code" space=2
yabai -m rule --add app="Hyper" space=2
yabai -m rule --add app="Spark" space=3
yabai -m rule --add app="^Notion" space=3
yabai -m rule --add app="Messages" space=4
yabai -m rule --add app="Tidal" space=4

yabai -m rule --add app="Spark" title!="Spark" manage=off space=3
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^1Password" manage=off
yabai -m rule --add app="^Web Inspector$" manage=off
yabai -m rule --add app="^Creative Cloud$" manage=off
yabai -m rule --add app="Alfred" manage=off
yabai -m rule --add app="Preview" manage=off
yabai -m rule --add app="Rocket" manage=off


echo "yabai configuration loaded.."