# Extra autostart processes
# exec-once = uwsm app -- my-service

# exec-once = sunsetr
exec-once = uwsm app -- kanshi
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
# Restart kanshi if it crashes
# exec-once = bash -c 'while true; do pgrep -x kanshi || uwsm app -- kanshi; sleep 5; done'

exec-once = ~/.config/hypr/scripts/padding.sh

# Initialize lid state and workspace padding on startup
exec = ~/.config/hypr/scripts/lid-toggle.sh $(grep -q closed /proc/acpi/button/lid/LID0/state 2>/dev/null && echo "close" || echo "open")
