# Application bindings
$terminal = uwsm app -- Ghostty.desktop
$browser = omarchy-launch-browser
$hyper = SUPER + CTRL + ALT + SHIFT

bindd = $hyper, A, Switch to workspace 1, workspace, 1
bindd = $hyper, S, Switch to workspace 2, workspace, 2
bindd = $hyper, D, Switch to workspace 3, workspace, 3
bindd = $hyper, F, Switch to workspace 4, workspace, 4
bindd = $hyper, Z, Switch to workspace 5, workspace, 5
bindd = $hyper, X, Switch to workspace 6, workspace, 6
bindd = $hyper, C, Switch to workspace 7, workspace, 7
bindd = $hyper, V, Switch to workspace 8, workspace, 8
bindd = $hyper, J, Move focus left, movefocus, l
bindd = $hyper, K, Move focus right, movefocus, r

bindd = SUPER, return, Terminal, exec, $terminal# --dir=$(omarchy-cmd-terminal-cwd)
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, uwsm app -- spotify
# bindd = SUPER, N, Neovim, exec, $terminal -e nvim
# bindd = SUPER, T, Activity, exec, $terminal -e btop
# bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
bindd = SUPER, O, Obsidian, exec, uwsm app -- obsidian -disable-gpu
bindd = SUPER, slash, Passwords, exec, uwsm app -- 1password

bindd = SUPER, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER, C, Calendar, exec, omarchy-launch-webapp "https://calendar.google.com/calendar/u/1/r"
bindd = SUPER, E, Email, exec, omarchy-launch-webapp "https://app.fastmail.com/mail/Inbox/"
bindd = SUPER, H, HelpScout, exec, omarchy-launch-webapp "https://secure.helpscout.net/inboxes/ca9f1c7108512ae1/views/8176762"
bindd = SUPER, L, Linear, exec, omarchy-launch-webapp "https://linear.app/rightmessage/view/active-issues-3ce931976036"
bindd = SUPER, R, RightMessage, exec, omarchy-launch-webapp "https://app.rightmessage.com/"
bindd = SUPER, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-webapp "https://web.whatsapp.com/"
bindd = SUPER, X, X, exec, omarchy-launch-webapp "https://x.com/"


# Overrides

bindd = $hyper, Q, Copy region, exec, hyprshot -m region --clipboard-only
unbind = , PRINT
bindd = , PRINT, Copy region, exec, hyprshot -m region --clipboard-only
bindd = $hyper, W, Screenshot of region, exec, omarchy-cmd-screenshot
bindd = $hyper, E, Screenshot of window, exec, omarchy-cmd-screenshot window
bindd = $hyper, R, Screenshot of display, exec, omarchy-cmd-screenshot output

bindd = $hyper, ESC, Screen record display, exec, omarchy-cmd-screenrecord output

# unbind = SUPER, V
bindd = $hyper, Y, Fullscreen, fullscreen

# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Launch apps, exec, vicinae

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, Space
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bindl = , switch:on:Lid Switch, exec, ~/.config/hypr/scripts/lid-toggle.sh close
bindl = , switch:off:Lid Switch, exec, ~/.config/hypr/scripts/lid-toggle.sh open

binds {
  allow_workspace_cycles = yes
}
