source = ~/.config/omarchy/themes/mainframe-night/hyprlock.conf


$inner_color = rgba(138,138,141,0.3)
$outer_color = rgba(234,234,234,0.5)

background {
    monitor =
    path = /home/brennandunn/.local/share/omarchy/themes/matte-black/backgrounds/1-matte-black.jpg
    #color = $color
}

# animations {
#     enabled = false
# }

input-field {
    monitor =
    size = 600, 100
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 4

    font_family = CaskaydiaMono Nerd Font
    font_color = $font_color

    placeholder_text =   Enter Password 󰈷 
    check_color = $check_color
    fail_text = <i>$PAMFAIL ($ATTEMPTS)</i>

    rounding = 0
    shadow_passes = 0
    fade_on_empty = false
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = CaskaydiaMono Nerd Font
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = CaskaydiaMono Nerd Font
  position = 0, 200
  halign = center
  valign = center
}

auth {
    fingerprint:enabled = true
}
