windowrule = tag +sharing, title:.*sharing your screen.*
windowrulev2 = tag +sharing, floating:1, class:^(chromium)$

windowrule = noborder, tag:sharing
windowrule = noblur, tag:sharing
windowrule = nodim, tag:sharing
windowrule = noshadow, tag:sharing
windowrule = noanim, tag:sharing
windowrule = noscreenshare, tag:sharing
windowrule = move 100%-w-20, tag:sharing
