
# Workspace 2 - Code
# Dynamic padding based on monitor - only applies on external monitors (not eDP-1)
#exec-once = ~/.config/hypr/scripts/monitor-workspace-watcher.sh

workspace = 1, gapsout:100 100 100 100
workspace = 2, gapsout:100 100 100 100

# Workspace 2 - Writing / Tasks

# Workspace 3 - Email
windowrule = workspace 3, class:eu.betterbird.Betterbird

# Workspace 4 - Chat

windowrule = workspace 4, class:discord
windowrule = workspace 4, class:slack
